//> using publish.organization "io.github.alexarchambault.scala-cli"
//> using publish.name "graalvm-execve"
//> using publish.computeVersion "git:tag"
//> using publish.repository "central-s01"
//> using publish.user "env:PUBLISH_USER"
//> using publish.password "env:PUBLISH_PASSWORD"
//> using publish.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/scala-cli/graalvm-execve"
//> using publish.versionControl "github:scala-cli/graalvm-execve"
//> using publish.developer "Alex Archambault|alexandre.archambault@gmail.com|https://github.com/alexarchambault"
